USE MUNDIALESFUTBOL
GO
CREATE TRIGGER BORRADO_PAIS ON PAIS INSTEAD OF DELETE AS
UPDATE PAIS
SET BORRADO = 'S'
WHERE ID_PAIS IN (SELECT DELETED.ID_PAIS 
					FROM DELETED);
GO

SELECT *
FROM PAIS         /*PASO 1 PARA PROBAR EL TRIGGER, ELEGIMOS UNO PARA ELIMINAR*/

DELETE
FROM PAIS		/*PASO 2 PARA PROBAR EL TRIGGER*/
WHERE ID_PAIS = 1

SELECT *
FROM PAIS		/*PASO 3 PARA PROBAR EL TRIGGER*/
