USE MUNDIALESFUTBOL

GO
CREATE FUNCTION CANTIDAD_DE_MUNDIALES(@NOM_PAIS VARCHAR(30))
	RETURNS INT
	AS
	BEGIN
	 DECLARE @NUMERO INT
	SET @NUMERO = ( SELECT COUNT(*)
					FROM SELECCION
					WHERE SELECCION.NOMBRE_SELECCION = @NOM_PAIS
				  );
	RETURN @NUMERO;
	END
GO
/*-----------------------CON ESTA FUNCION CONSULTAMOS LA CANTIDAD DE MUNDIALES*/

SELECT dbo.CANTIDAD_DE_MUNDIALES('Argelia') AS CANT_MUNDIALES_POR_PAIS
/*----------------------------------CON ESTO EJECUTAMOS LA FUNCION*/
