USE MUNDIALESFUTBOL
GO
CREATE VIEW CANTIDAD_SELECCIONES AS 
(SELECT MAX(NUMERO.RES) AS NUM_MAX
								FROM (
										SELECT COUNT(DISTINCT S.ID_PAIS) AS RES
										FROM DT INNER JOIN SELECCION AS S ON (DT.ID_DT = S.ID_DT) 
										INNER JOIN MUNDIAL AS M ON  (S.ANIO = M.ANIO)
										GROUP BY DT.ID_DT
									 ) AS NUMERO
)
GO

SELECT DT.ID_DT,DT.APELLIDO_DT,DT.NOMBRE_DT,COUNT(DISTINCT S.ID_PAIS) AS CANTIDAD_DE_SELECCIONES_DIRIGIDAS
FROM DT INNER JOIN SELECCION AS S ON (DT.ID_DT = S.ID_DT)
GROUP BY DT.ID_DT,DT.APELLIDO_DT,DT.NOMBRE_DT
HAVING COUNT(DISTINCT S.ID_PAIS) = (SELECT *
									FROM CANTIDAD_SELECCIONES)

