USE MUNDIALESFUTBOL
GO
CREATE FUNCTION MINIMA_CANTIDAD (@NUMMUND INT)
RETURNS TABLE
AS
RETURN
	(
	SELECT MIN(NUM.RES) AS CANT_MIN
	FROM (SELECT COUNT(G.ID_GOL) AS RES
			FROM MUNDIAL AS M INNER JOIN SELECCION AS S ON(M.ANIO = S.ANIO)
				INNER JOIN PERTENECE AS P 
				ON (P.ID_SELECCION = S.ID_SELECCION) INNER JOIN JUGADOR AS J ON (P.ID_JUGADOR = J.ID_JUGADOR)
				INNER JOIN GOL AS G ON (G.ID_JUGADOR = J.ID_JUGADOR)
			WHERE G.A_FAVOR = 'S' AND S.ANIO = @NUMMUND
			GROUP BY S.ID_SELECCION) AS NUM
	)
GO

SELECT S.ANIO,S.NOMBRE_SELECCION, COUNT(G.A_FAVOR) AS CDAD_GOLES_POR_MUNDIAL
FROM MUNDIAL AS M INNER JOIN SELECCION AS S ON(M.ANIO = S.ANIO)
     INNER JOIN PERTENECE AS P 
     ON (P.ID_SELECCION = S.ID_SELECCION) INNER JOIN JUGADOR AS J ON (P.ID_JUGADOR = J.ID_JUGADOR)
     INNER JOIN GOL AS G ON (G.ID_JUGADOR = J.ID_JUGADOR)
WHERE G.A_FAVOR = 'S'
GROUP BY S.ANIO, S.ID_SELECCION,S.NOMBRE_SELECCION
HAVING COUNT(G.A_FAVOR) = (SELECT *
							FROM MINIMA_CANTIDAD(S.ANIO))
ORDER BY S.ANIO
DROP FUNCTION MINIMA_CANTIDAD
