USE MUNDIALESFUTBOL

SELECT TOP 5 PA.NOMBRE,COUNT(PAR.ID_PARTIDO) AS FINALES_JUGADAS
FROM PAIS AS PA INNER JOIN SELECCION AS SE ON (PA.ID_PAIS = SE.ID_PAIS)    
       INNER JOIN PARTIDO AS PAR ON 
		(PAR.ID_SELECCION_LOCAL = SE.ID_SELECCION OR 
		PAR.ID_SELECCION_VISITANTE = SE.ID_SELECCION) INNER JOIN 
		INSTANCIA AS INS ON (INS.ID_INSTANCIA = PAR.ID_INSTANCIA)
WHERE INS.DESCRIPCION = 'FINAL'
GROUP BY PA.NOMBRE
ORDER BY COUNT(PAR.ID_PARTIDO) DESC
