USE MUNDIALESFUTBOL

SELECT TOP 3 J.NOMBRE_JUG,J.APELLIDO_JUG,S.NOMBRE_SELECCION,COUNT(G.A_FAVOR) AS CANTIDAD_DE_GOLES
FROM JUGADOR AS J INNER JOIN GOL AS G ON (J.ID_JUGADOR = G.ID_JUGADOR) 
		INNER JOIN PERTENECE AS P ON (P.ID_JUGADOR = J.ID_JUGADOR)
		INNER JOIN SELECCION AS S ON (P.ID_SELECCION = S.ID_SELECCION)
GROUP BY J.ID_JUGADOR, J.APELLIDO_JUG,J.NOMBRE_JUG,S.NOMBRE_SELECCION
ORDER BY COUNT(G.A_FAVOR) DESC
