USE MUNDIALESFUTBOL
GO
CREATE PROCEDURE DATOS_JUGADOR @JUG INTEGER
	AS
	SELECT SEL.ANIO, PER.NRO_CAMISETA, PER.TITULARIDAD
	FROM SELECCION AS SEL INNER JOIN PERTENECE AS PER
 ON (SEL.ID_SELECCION = PER.ID_SELECCION)
	WHERE PER.ID_JUGADOR = @JUG
GO

EXECUTE DATOS_JUGADOR [18]  /* Ejemplo*/
