CREATE DATABASE MUNDIALESFUTBOL;       /*PRIMERO DEBO CORRER ESTA LINEA SOLA, LUEGO LA BORRAN Y CORREN EL RESTO DE LAS LINEAS*/
USE MUNDIALESFUTBOL;					

CREATE TABLE CIUDAD( 
ID_CIUDAD INT PRIMARY KEY,
DESCRIPCION VARCHAR(30)
);

CREATE TABLE PAIS( 
ID_PAIS INT PRIMARY KEY,
BORRADO CHAR,
NOMBRE VARCHAR(50)
);

CREATE TABLE MUNDIAL( 
ANIO INT PRIMARY KEY
);

CREATE TABLE ES_SEDE_DE(
ANIO INT,
ID_PAIS INT,
FOREIGN KEY(ANIO) REFERENCES MUNDIAL(ANIO),
FOREIGN KEY(ID_PAIS) REFERENCES PAIS(ID_PAIS), 
PRIMARY KEY (ANIO, ID_PAIS)
);

CREATE TABLE INSTANCIA( 
ID_INSTANCIA INT PRIMARY KEY,
DESCRIPCION  VARCHAR(30)
);

CREATE TABLE ESTADIO( 
ID_ESTADIO INT PRIMARY KEY,
NOMBRE VARCHAR(30),
ID_CIUDAD INT,
FOREIGN KEY(ID_CIUDAD) REFERENCES CIUDAD(ID_CIUDAD)
);


CREATE TABLE DT(
ID_DT INT PRIMARY KEY,
NOMBRE_DT VARCHAR(30),
APELLIDO_DT VARCHAR(30),
FECHA_DE_NAC DATE
);

CREATE TABLE SELECCION(
ID_SELECCION INT PRIMARY KEY,
NOMBRE_SELECCION VARCHAR(30),
TARJETA_AMARILLA INT,
TARJETA_ROJA INT,
ID_PAIS INT,
ANIO INT,
ID_DT INT,
FOREIGN KEY(ID_DT) REFERENCES DT(ID_DT),
FOREIGN KEY(ID_PAIS) REFERENCES PAIS(ID_PAIS),
FOREIGN KEY(ANIO) REFERENCES MUNDIAL(ANIO)
);

CREATE TABLE PARTIDO( 
ID_PARTIDO INT PRIMARY KEY,
FECHA_PART DATE,
HORA_PART TIME,
ID_INSTANCIA INT,
ID_ESTADIO INT,
ID_SELECCION_LOCAL INT,
ID_SELECCION_VISITANTE INT,
FOREIGN KEY(ID_INSTANCIA) REFERENCES INSTANCIA(ID_INSTANCIA),
FOREIGN KEY(ID_ESTADIO) REFERENCES ESTADIO(ID_ESTADIO),
FOREIGN KEY(ID_SELECCION_LOCAL) REFERENCES SELECCION(ID_SELECCION),
FOREIGN KEY(ID_SELECCION_VISITANTE) REFERENCES SELECCION(ID_SELECCION)
);

CREATE TABLE JUGADOR( 
ID_JUGADOR INT PRIMARY KEY,
NOMBRE_JUG VARCHAR(30),
APELLIDO_JUG VARCHAR(30),
FECHA_DE_NAC DATE
);

CREATE TABLE PERTENECE( 
ID_JUGADOR INT,
ID_SELECCION INT,
NRO_CAMISETA INT,
TITULARIDAD CHAR,
PRIMARY KEY(ID_JUGADOR,ID_SELECCION),
FOREIGN KEY(ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR),
FOREIGN KEY(ID_SELECCION) REFERENCES SELECCION(ID_SELECCION)
);

CREATE TABLE TIPO_GOL( 
ID_TIPO_GOL INT PRIMARY KEY,
DESCRIPCION VARCHAR(30)
);

CREATE TABLE GOL(		
ID_GOL INT ,            
A_FAVOR CHAR,
MINUTO VARCHAR(4),
ID_JUGADOR INT ,
ID_PARTIDO INT ,
ID_TIPO_DE_GOL INT,
PRIMARY KEY (ID_JUGADOR,ID_PARTIDO,ID_GOL),
FOREIGN KEY(ID_JUGADOR) REFERENCES JUGADOR(ID_JUGADOR),
FOREIGN KEY(ID_PARTIDO) REFERENCES PARTIDO(ID_PARTIDO),
FOREIGN KEY(ID_TIPO_DE_GOL) REFERENCES TIPO_GOL(ID_TIPO_GOL)
);
